crd:
  group: bus.stei.gr
  name: anycables
  version: v1alpha1
  namespace: YOUR_NAMESPACE_HERE
helm:
  chart: chart
  namespace: YOUR_NAMESPACE_HERE
  tiller: tiller-deploy.kube-system:44134
  releasePrefix: anycable