{{- $app := printf "%s-websocket" .Values.resource.name -}}
{{- $default := .Values.default.websocket -}}
{{- $spec := .Values.resource.spec.websocket -}}
{{- $server := .Values.resource.spec.server -}}
{{- $server_default := .Values.default.server -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ $app }}
  labels:
    app: {{ $app }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ default .Values.default.size .Values.resource.spec.size }}
  template:
    metadata:
      labels:
        app: {{ .Values.resource.name }}
        resource: {{ $app }}
    spec:
{{- if $spec.nodeSelector }}
      nodeSelector:
{{ toYaml $spec.nodeSelector | indent 8 }}
{{ end -}}
{{- if $spec.tolerations }}
      tolerations:
{{ toYaml $spec.tolerations | indent 8 }}
{{ end }}
      containers:
      - name: websocket{{ with $default }}{{ if $spec.image }}
        image: {{ default .image.name $spec.image.name }}:{{ default .image.tag $spec.image.tag }}
        imagePullPolicy: {{ default .image.pullPolicy $spec.image.pullPolicy }}{{ else }}
        image: {{ .image.name }}:{{ .image.tag }}
        imagePullPolicy: {{ .image.pullPolicy }}{{ end }}{{ end }}
        ports:
        - containerPort: 8080
          name: websocket
        envFrom:
          - configMapRef:
              name: {{ $app }}
        env:
          - name: ANYCABLE_RPC_HOST
            value: {{ .Values.resource.name }}-anycable:{{ default $server_default.port $server.port }}
          - name: ANYCABLE_REDIS_URL
            valueFrom:
              secretKeyRef:
                name: {{ default ( printf "%s-redis-credentials" .Values.resource.name ) .Values.resource.spec.credentials }}
                key: REDIS_URL
